"""Recompute every number used in the slides from Gold and write docs/presentation_facts.md.

Run after run_local.sh:  python docs/build_fact_sheet.py
Definitions mirror semantic_model/measures.dax so slide numbers = report numbers.
"""
import json
import os
from pathlib import Path

import pandas as pd

ROOT = Path(os.environ.get("REPO_ROOT", Path(__file__).resolve().parents[1]))
GOLD = ROOT / "data" / "gold"
g = lambda t: pd.read_parquet(GOLD / t)

fl, src, dealer, veh, dq = g("fact_leads"), g("dim_lead_source"), g("dim_dealer"), g("dim_vehicle"), g("dq_results")
fl = fl.merge(src, on="source", how="left").merge(dealer, on="dealer_id", how="left").merge(veh, on="vehicle_id", how="left")
metrics = json.loads((ROOT / "ai_product/model/metrics.json").read_text())

pct = lambda x: f"{x:.1%}"
conv = lambda d: d["is_won"].sum() / len(d) if len(d) else float("nan")
conv_closed = lambda d: d["is_won"].sum() / (d["is_won"].sum() + d["is_lost"].sum())
out = []
w = out.append


def table(df):
    w(df.to_markdown(index=False))
    w("")


w("# Presentation facts — recomputed from Gold\n")
w("Generated by `docs/build_fact_sheet.py` (seed 42 data). Every number on a slide should appear here.\n")

# --- Headline
w("## Headline (slide 2)\n")
created = pd.to_datetime(fl["created_at"])
open_ = fl[fl["is_open"]]
adv_open = open_.groupby("advisor_id").size()
stale = open_[(open_["lead_age_days"] > 30) & (open_["days_since_last_interaction"] > 14)]
table(pd.DataFrame([
    ["Leads", f"{len(fl):,}"],
    ["Period", f"{created.min():%b %Y} – {created.max():%b %Y}"],
    ["Customers / dealers (excl. UNK) / advisors", f"{fl.customer_id.nunique():,} / {dealer[dealer.dealer_id!='UNK'].shape[0]} / {fl.advisor_id.nunique()}"],
    ["Won / lost / open", f"{fl.is_won.sum():,} / {fl.is_lost.sum():,} / {fl.is_open.sum():,}"],
    ["Lead-to-sale conversion (won / all)", pct(conv(fl))],
    ["Conversion, closed leads (won / (won+lost))", pct(conv_closed(fl))],
    ["Leads with test drive / offer / sale", f"{fl.has_test_drive.sum():,} / {fl.has_offer.sum():,} / {fl.has_sale.sum():,}"],
    ["Open leads per advisor (min–median–max)", f"{adv_open.min()}–{int(adv_open.median())}–{adv_open.max()}"],
    ["Stale open leads (age>30d, quiet>14d)", f"{len(stale):,} of {len(open_):,}"],
    ["Revenue (bn TRY)", f"{fl.sale_amount_try.sum()/1e9:.2f}"],
], columns=["metric", "value"]))

# --- Channels
w("## By source (slides 2, 9)\n")
by = fl.groupby(["source_group", "source_label"]).apply(lambda d: pd.Series({
    "leads": len(d), "share": len(d) / len(fl), "conversion": conv(d), "closed_conv": conv_closed(d),
    "median_resp_h": d.first_response_hours.median()})).reset_index().sort_values("leads", ascending=False)
for c in ["share", "conversion", "closed_conv"]:
    by[c] = by[c].map(pct)
by["median_resp_h"] = by["median_resp_h"].round(1)
table(by)
dig = fl.groupby("is_digital").apply(lambda d: pd.Series({"leads": len(d), "share": pct(len(d)/len(fl)), "conversion": pct(conv(d))})).reset_index()
table(dig)

# --- Funnel
w("## Funnel (slide 8, report page 1)\n")
table(pd.DataFrame([
    ["Leads", len(fl)], ["Contacted", fl.first_contact_at.notna().sum()], ["Test drive", fl.has_test_drive.sum()],
    ["Offer", fl.has_offer.sum()], ["Won", fl.is_won.sum()]], columns=["stage", "leads"]).assign(
    of_leads=lambda d: (d.leads / len(fl)).map(pct)))

# --- Dealers
w("## Dealers (slide 9, report page 2)\n")
net = conv(fl)
dl = fl.groupby(["dealer_label", "dealer_type", "region"]).apply(lambda d: pd.Series({"leads": len(d), "conv": conv(d)})).reset_index()
dl["vs_network"] = dl.conv / net
dl["flag"] = pd.cut(dl.vs_network, [-1, .75, 1.25, 99], labels=["At risk", "On track", "Star"], right=False)
dl = dl.sort_values("conv")
dl["conv"] = dl.conv.map(pct); dl["vs_network"] = dl.vs_network.map(lambda x: f"{x:.0%}")
table(dl)

w("### Response time × digital (slide 9)\n")
rt = fl.groupby(["response_band_order", "response_band", "is_digital"]).apply(conv).unstack("is_digital").reset_index()
rt.columns = ["order", "response_band", "non_digital", "digital"]
table(rt.drop(columns="order").assign(non_digital=lambda d: d.non_digital.map(pct), digital=lambda d: d.digital.map(pct)))

# --- Vehicles
w("## Models & price (slide 10/11, report page 3)\n")
pb = fl.groupby(["price_band_order", "price_band"]).apply(lambda d: pd.Series({"leads": len(d), "conv": pct(conv(d))})).reset_index().drop(columns="price_band_order")
table(pb)
q = fl[fl.is_won].assign(q=pd.to_datetime(fl.sale_date).dt.to_period("Q").astype(str)).groupby("q").is_electrified.mean().map(pct).reset_index()
q.columns = ["quarter", "electrified share of sales"]
table(q)
table(fl.groupby("brand").apply(lambda d: pd.Series({"leads": len(d), "won": d.is_won.sum(), "conv": pct(conv(d))})).reset_index())

# --- DQ
w("## Data quality (slides 6, 11, report page 4)\n")
table(pd.DataFrame([
    ["Checks logged", len(dq)],
    ["Rows repaired or flagged (sum of failed_rows)", f"{dq.failed_rows.sum():,}"],
    ["Checks by severity", ", ".join(f"{k} {v}" for k, v in dq.severity.value_counts().items())],
    ["Leads carrying ≥1 dq_flag in Gold", f"{(fl.dq_flag_count > 0).sum():,}"],
    ["Leads on UNK dealer", f"{(fl.dealer_id == 'UNK').sum():,}"],
], columns=["metric", "value"]))
table(dq.sort_values("failed_rows", ascending=False)[["check_name", "table_name", "failed_rows", "severity", "action"]])

# --- Model
w("## Lead scorer (slide 16)\n")
rows = []
for k in ["overall", "before_offer_stage", "after_offer_stage"]:
    m = metrics[k]
    rows.append([k, m["n"], pct(m["base_rate"]), f"{m['auc']:.3f}", f"{m['pr_auc']:.3f}", f"{m['lift_top10pct']:.2f}×", pct(m["precision_top10pct"])])
table(pd.DataFrame(rows, columns=["slice", "n", "base rate", "AUC", "PR-AUC", "lift top10%", "precision top10%"]))
w(f"Temporal split at {metrics['split_date']}; {metrics['n_train']:,} training snapshots.\n")
fi = pd.read_csv(ROOT / "ai_product/model/feature_importance.csv").head(10)
table(fi)
cal = pd.read_csv(ROOT / "ai_product/model/calibration.csv")
table(cal)

# --- Eval
w("## Extractor eval (slide 15)\n")
w((ROOT / "ai_product/eval/RESULTS.md").read_text().split("## Keyword rules (signals.py)")[1].split("## Reading")[0].strip())
w("")

# --- Traps: things the interviewer may notice
w("## Things to be ready for\n")
w(f"* Funnel is not monotonic: {int((fl.has_offer & ~fl.has_test_drive).sum()):,} leads got an offer without a test drive, "
  "so 'Offer' > 'Test drive'. The stages are independent flags, not a strict sequence.")
w(f"* {int((pd.to_datetime(fl[fl.is_won].sale_date) < created.min().normalize()).sum())} won leads have a sale date before the "
  "first lead (DQ check sale_date_before_lead_created); the electrified chart filters quarters with < 20 units.")
w(f"* Median time to first response: digital {fl[fl.is_digital].first_response_hours.median():.1f} h vs "
  f"non-digital {fl[~fl.is_digital].first_response_hours.median():.1f} h — why response time is split by channel.")
w("")

(ROOT / "docs/presentation_facts.md").write_text("\n".join(out), encoding="utf-8")
print("wrote docs/presentation_facts.md")
